# Generated by Django 6.0.5 on 2026-05-24 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_tax_ai_tip_usage'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taxaitipusage',
            new_name='payroll_tax_employe_edc905_idx',
            old_name='payroll_tax_employe_8a1f2c_idx',
        ),
    ]
