# Generated by Django 6.0.5 on 2026-05-23 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='magic_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
