# Generated by Django 6.0.5 on 2026-05-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_live_watch_media'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiinterviewmediablob',
            new_name='recruitment_session_00f523_idx',
            old_name='recruit_blob_sess_kind',
        ),
        migrations.RenameIndex(
            model_name='aiinterviewmediachunk',
            new_name='recruitment_session_d2b23e_idx',
            old_name='recruit_chu_sess_kind_seq',
        ),
        migrations.AlterField(
            model_name='aiinterviewsession',
            name='include_assessment',
            field=models.BooleanField(default=False, help_text='HR opted in at invite time; assessment is not sent unless this is true.'),
        ),
    ]
