# Generated by Django 6.0.5 on 2026-05-27 13:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_core_outbou_tenant__8c4f21_idx_core_outbou_tenant__bfd9c0_idx_and_more'),
        ('recruitment', '0011_astra_tts_blob_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePrebakedQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('difficulty_tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme_hard', 'Extreme Hard')], max_length=32)),
                ('question_text', models.TextField()),
                ('ideal_benchmarked_response', models.TextField()),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_prebaked_questions', to='recruitment.recruitmentcampaign')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prebaked_questions', to='recruitment.candidate')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prebaked_questions', to='recruitment.aiinterviewsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CandidateLiveResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_order', models.PositiveIntegerField()),
                ('transcript_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('answered', 'Answered'), ('skipped', 'Skipped'), ('repeated', 'Repeated'), ('timeout', 'Timeout')], default='answered', max_length=16)),
                ('silence_seconds', models.PositiveIntegerField(default=0)),
                ('repeated_count', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_responses', to='recruitment.candidate')),
                ('interview_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_responses', to='recruitment.aiinterviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_responses', to='recruitment.aiinterviewsession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('prebaked_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_responses', to='recruitment.candidateprebakedquestion')),
            ],
            options={
                'ordering': ['question_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentCampaignAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('jd_extract', 'JD Extract')], default='jd_extract', max_length=32)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('extracted_text', models.TextField(blank=True, default='')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='recruitment.recruitmentcampaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentCampaignQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('source', models.CharField(choices=[('jd_baseline', 'JD Baseline')], default='jd_baseline', max_length=32)),
                ('difficulty_tier', models.CharField(blank=True, default='', max_length=32)),
                ('question_text', models.TextField()),
                ('ideal_answer', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_questions', to='recruitment.recruitmentcampaign')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='candidateprebakedquestion',
            index=models.Index(fields=['session', 'order'], name='recruitment_session_5f8d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateprebakedquestion',
            index=models.Index(fields=['candidate', 'created_at'], name='recruitment_candida_f8c24e_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidateprebakedquestion',
            constraint=models.UniqueConstraint(fields=('candidate', 'session', 'order'), name='uniq_candidate_session_prebaked_order'),
        ),
        migrations.AddIndex(
            model_name='candidateliveresponse',
            index=models.Index(fields=['session', 'question_order'], name='recruitment_session_0ab8dd_idx'),
        ),
        migrations.AddIndex(
            model_name='candidateliveresponse',
            index=models.Index(fields=['candidate', 'created_at'], name='recruitment_candida_1ce88b_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcampaignattachment',
            index=models.Index(fields=['campaign', 'kind'], name='recruitment_campaig_f739f2_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcampaignquestion',
            index=models.Index(fields=['campaign', 'source', 'order'], name='recruitment_campaig_f647f7_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentcampaignquestion',
            constraint=models.UniqueConstraint(fields=('campaign', 'order', 'source'), name='uniq_campaign_question_source_order'),
        ),
    ]
