# Generated by Django 6.0.5 on 2026-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_failed_login_attempts_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_encoding',
            field=models.JSONField(blank=True, help_text='128-dimensional face encoding vector', null=True),
        ),
    ]
