# Generated by Django 6.0.5 on 2026-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_face_encoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='authsession',
            name='login_method',
            field=models.CharField(choices=[('password', 'Password'), ('totp', 'TOTP'), ('passkey', 'Passkey'), ('face_scan', 'Face Scan')], default='password', max_length=50),
        ),
    ]
