# Generated by Django 6.0.5 on 2026-05-23 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tenant_email_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='default_env_key', max_length=255, unique=True)),
                ('wrapped_key', models.TextField(help_text='AES-GCM wrapped data key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnvConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(help_text="Module name e.g., 'SMTP', 'DATABASE'", max_length=100, unique=True)),
                ('encrypted_config', models.TextField(help_text='AES-GCM encrypted JSON config mapped to base64')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
