# Generated by Django 6.0.5 on 2026-05-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicaltenant_jurisdiction_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='systemauditlog',
            new_name='core_system_tenant__a2d3af_idx',
            old_name='core_sal_tenant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='systemauditlog',
            new_name='core_system_module_bf22e0_idx',
            old_name='core_sal_module_created_idx',
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='enabled_jurisdictions',
            field=models.JSONField(blank=True, default=list, help_text='Payroll jurisdictions enabled for this tenant: IN, US, CA'),
        ),
    ]
