# Generated by Django 6.0.5 on 2026-05-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tenantaddon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltenant',
            name='allow_employee_variable_override',
            field=models.BooleanField(default=True, help_text='If true, per-employee variable_pay_enabled can override tenant default'),
        ),
        migrations.AlterField(
            model_name='historicaltenant',
            name='variable_pay_enabled',
            field=models.BooleanField(default=False, help_text='Company-wide: allow variable pay component in salary structures'),
        ),
    ]
