# Generated by Django 6.0.5 on 2026-05-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_e2ee_redis_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='subscription_plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', help_text="Tenant's active subscription plan", max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='subscription_plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='starter', help_text="Tenant's active subscription plan", max_length=20),
        ),
    ]
