# Generated by Django 6.0.5 on 2026-05-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tenant_email_outbound_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='core_outbou_tenant__bfd9c0_idx',
            old_name='core_outbou_tenant__8c4f21_idx',
        ),
        migrations.RenameIndex(
            model_name='outboundemaillog',
            new_name='core_outbou_tenant__94a75d_idx',
            old_name='core_outbou_tenant__a1b2c3_idx',
        ),
        migrations.AlterField(
            model_name='tenantemailsettings',
            name='notify_roles',
            field=models.JSONField(blank=True, default=list, help_text='Role names notified on email events, e.g. Company Admin, HR Admin'),
        ),
    ]
