# Generated by Django 6.0.5 on 2026-05-23 12:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('core', '0008_authsession_payload_key_wrapped'),
        ('employees', '0002_alter_employee_user'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='punch_source',
            field=models.CharField(choices=[('Web', 'Web'), ('Mobile', 'Mobile'), ('Biometric', 'Biometric')], default='Web', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_selfies/'),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_regularizations', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='attendanceregularization',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='method',
            field=models.CharField(choices=[('QR', 'QR'), ('GPS', 'GPS'), ('Manual', 'Manual'), ('Web', 'Web')], default='Web', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Half Day', 'Half Day')], default='Present', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendanceregularization',
            name='attendance_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to='attendance.attendancelog'),
        ),
        migrations.AlterField(
            model_name='geofence',
            name='radius_meters',
            field=models.IntegerField(default=50),
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_radius_meters', models.IntegerField(default=50)),
                ('require_gps', models.BooleanField(default=True)),
                ('require_selfie', models.BooleanField(default=False)),
                ('allow_web_punch', models.BooleanField(default=True)),
                ('allow_regularization', models.BooleanField(default=True)),
                ('company_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_settings', to='organization.companyprofile')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
