# Generated by Django 6.0.5 on 2026-05-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_field_tracking_and_office_hours'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fieldlocationping',
            new_name='attendance__tenant__e3715e_idx',
            old_name='att_fping_tenant_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldlocationping',
            new_name='attendance__tenant__a92bb8_idx',
            old_name='att_fping_tenant_rec_idx',
        ),
    ]
