# Generated by Django 6.0.5 on 2026-05-23 10:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_authsession_ip_address_authsession_location_city_and_more'),
        ('employees', '0002_alter_employee_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerAppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, unique=True)),
                ('min_supported', models.CharField(max_length=50)),
                ('download_url', models.URLField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackerDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_uuid', models.CharField(max_length=64)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('os_name', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('mac_address_hash', models.CharField(blank=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('is_trusted', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_devices', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WFHPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('require_hr_approval', models.BooleanField(default=True)),
                ('screenshot_interval_seconds', models.PositiveIntegerField(default=15)),
                ('idle_threshold_seconds', models.PositiveIntegerField(default=300)),
                ('heartbeat_interval_seconds', models.PositiveIntegerField(default=60)),
                ('heartbeat_miss_seconds', models.PositiveIntegerField(default=180)),
                ('screenshot_retention_days', models.PositiveIntegerField(default=30)),
                ('allow_pause', models.BooleanField(default=True)),
                ('capture_window_title', models.BooleanField(default=False)),
                ('max_daily_screenshot_count', models.PositiveIntegerField(default=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'verbose_name_plural': 'WFH policies',
            },
        ),
        migrations.CreateModel(
            name='WFHRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_date', models.DateField(default=django.utils.timezone.localdate)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('manager_approved', 'Manager Approved'), ('hr_approved', 'HR Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by_hr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wfh_hr_approvals', to=settings.AUTH_USER_MODEL)),
                ('approved_by_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wfh_manager_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_requests', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WFHApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('wfh_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='wfh.wfhrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('stopped', 'Stopped'), ('interrupted', 'Interrupted')], default='active', max_length=20)),
                ('total_duration', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('active_duration', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('idle_duration', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('screenshot_count', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wfh.trackerdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('wfh_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='wfh.wfhrequest')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotCapture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('captured_at', models.DateTimeField()),
                ('storage_key', models.CharField(max_length=512)),
                ('thumbnail_key', models.CharField(blank=True, max_length=512)),
                ('monitor_number', models.PositiveSmallIntegerField(default=1)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('encrypted', models.BooleanField(default=True)),
                ('window_title', models.CharField(blank=True, max_length=512)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='wfh.worksession')),
            ],
        ),
        migrations.CreateModel(
            name='IdleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idle_start_time', models.DateTimeField()),
                ('idle_end_time', models.DateTimeField(blank=True, null=True)),
                ('idle_duration', models.PositiveIntegerField(default=0, help_text='Seconds')),
                ('reason', models.CharField(default='threshold_exceeded', max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_logs', to='wfh.worksession')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summary_date', models.DateField()),
                ('active_seconds', models.PositiveIntegerField(default=0)),
                ('idle_seconds', models.PositiveIntegerField(default=0)),
                ('screenshot_count', models.PositiveIntegerField(default=0)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_summaries', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wfh.worksession')),
            ],
        ),
        migrations.CreateModel(
            name='WorkSessionHeartbeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('heartbeat_at', models.DateTimeField()),
                ('app_status', models.CharField(default='active', max_length=50)),
                ('battery_status', models.CharField(blank=True, max_length=50)),
                ('network_status', models.CharField(blank=True, max_length=50)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wfh.trackerdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='wfh.worksession')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(default='wfh_tracking_v1', max_length=50)),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wfh_consents', to='employees.employee')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'consent_type', 'revoked_at'], name='wfh_employe_employe_326caa_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrackerAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'created_at'], name='wfh_tracker_tenant__9d76cd_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trackerdevice',
            index=models.Index(fields=['device_uuid'], name='wfh_tracker_device__9830a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackerdevice',
            unique_together={('tenant', 'device_uuid')},
        ),
        migrations.AddIndex(
            model_name='wfhrequest',
            index=models.Index(fields=['tenant', 'employee', 'status'], name='wfh_wfhrequ_tenant__b10e47_idx'),
        ),
        migrations.AddIndex(
            model_name='wfhrequest',
            index=models.Index(fields=['tenant', 'start_date', 'end_date'], name='wfh_wfhrequ_tenant__98520a_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['employee', 'status'], name='wfh_workses_employe_44021d_idx'),
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['tenant', 'start_time'], name='wfh_workses_tenant__db9ad6_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshotcapture',
            index=models.Index(fields=['session', 'captured_at'], name='wfh_screens_session_e89a62_idx'),
        ),
        migrations.AddIndex(
            model_name='screenshotcapture',
            index=models.Index(fields=['employee', 'captured_at'], name='wfh_screens_employe_355bc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='screenshotcapture',
            constraint=models.UniqueConstraint(fields=('session', 'checksum_sha256'), name='uniq_session_screenshot_checksum'),
        ),
        migrations.AlterUniqueTogether(
            name='activitysummary',
            unique_together={('employee', 'summary_date', 'session')},
        ),
        migrations.AddIndex(
            model_name='worksessionheartbeat',
            index=models.Index(fields=['session', 'heartbeat_at'], name='wfh_workses_session_7ea896_idx'),
        ),
    ]
