# Generated by Django 6.0.5 on 2026-05-23 11:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_authsession_payload_key_wrapped'),
        ('employees', '0002_alter_employee_user'),
        ('wfh', '0004_worksessionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerBugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('screenshot_key', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(default='open', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='worksessionevent',
            new_name='wfh_workses_session_2cc30a_idx',
            old_name='wfh_wse_sess_occ_idx',
        ),
        migrations.RenameIndex(
            model_name='worksessionevent',
            new_name='wfh_workses_employe_74dd8f_idx',
            old_name='wfh_wse_emp_occ_idx',
        ),
        migrations.AddField(
            model_name='trackerbugreport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_bug_reports', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='trackerbugreport',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddIndex(
            model_name='trackerbugreport',
            index=models.Index(fields=['tenant', 'reported_at'], name='wfh_tracker_tenant__f46aa6_idx'),
        ),
    ]
