# Generated by Django 6.0.5 on 2026-05-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wfh', '0005_trackerbugreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='paused_duration',
            field=models.PositiveIntegerField(default=0, help_text='Seconds'),
        ),
    ]
