# Generated by Django 6.0.5 on 2026-05-24 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_type_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetype',
            name='tracking_interval_minutes',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
